services:
  mongo:
    image: mongo:8.0.6
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env

  # bot:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: crypto-bot
  #   depends_on:
  #     - mongo
  #   environment:
  #     MONGO_USER: ${MONGO_USER}
  #     MONGO_PASSWORD: ${MONGO_PASSWORD}
  #     MONGO_HOST: mongo:27017
  #     MONGO_DATABASE: ${MONGO_DATABASE}
  #     # Outros envs como BINANCE_API_KEY etc.
  #   env_file:
  #     - .env

volumes:
  mongo_data:
