services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    env_file:
      - ./backend/.env

  bot:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crypto-bot
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      BINANCE_API_KEY: ${BINANCE_API_KEY}
      BINANCE_API_SECRET: ${BINANCE_API_SECRET}
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    command: ["/app/crypto-bot"]
    restart: unless-stopped

volumes:
  pg_data:
